### ISSUE TITLE
Authentication using SQ 5.3 tokens - why not SSO?

### ISSUE THREAD

**Issue by Bertk** [TrimbleSolutionsCorporation/VSSonarQubeExtension#206]
After the upgrade to SQ 5.3 I could not connect to SQ5.3 server using "account+password".
SQ 5.3 has another way for authentication 'user tokens' and with this approach I could connect and access the SQ data.

We use the LDAP plugin (see http://blogs.msdn.com/b/visualstudioalm/archive/2015/11/13/support-for-active-directory-and-single-sign-on-sso-in-the-sonarqube-ldap-plugin.aspx).
Is it possible to use a SSO ?

**Comment by jmecosta** [comment]
i can authenticate with username + password in our systems when server is having sso. not sure how can i debug this, can you set the environment varialbe VSSONAREXTENSIONDEBUGVERBOSE and check from C:\Users\users\AppData\Roaming\VSSonarExtension in the created log what is the exception that is thrown?

**Comment by Bertk** [comment]
I will check this week but it would be a nice feature to use the windows login credentials of the existing session - in other words no configuration of any secret.
