### ISSUE TITLE
Update reference to sonar-cxx-msbuild-tasks version 1.9.2. RC1+

### ISSUE THREAD

**Issue by McMlok** [TrimbleSolutionsCorporation/VSSonarQubeExtension#213]
Hello,

can you update reference to sonar-cxx-msbuild-tasks  to version 1.9.2 RC1 or above? It's because when this tool is used on computer behind corporate proxy it always try to download some dependencies and it fail or want proxy username and password.

I updated sonar-cxx-msbuild-tasks and my update was merged and released as 1.9.2 RC1 version.

Thanks

**Comment by jmecosta** [comment]
1.9.2 is done, you can setup in options of the extension to use this
version. i will leave this open so i dont forget to update to last version
when i release the next version.


thanks
