### ISSUE TITLE
crash when adding tag and move the cursor up and down

### ISSUE THREAD

**Issue by jmecosta** [TrimbleSolutionsCorporation/VSSonarQubeExtension#243]

**Comment by Bertk** [comment]
The VS crash might not be related to the navigation but to updates of tag values.
![sqale-editor pgn](https://cloud.githubusercontent.com/assets/2315215/14058847/1a86f2cc-f32e-11e5-9c72-52623b00f6f7.png)
I removed the duplicate entry - By the way I am not aware adding this. I add "clumsy" and VS crashed. 
I noticed some more rules with duplicate tags which were created by the 'tag editor'.

**Comment by jmecosta** [comment]
fix also in the plugin: https://github.com/jmecsoftware/QualityProfileEditorPlugin/issues/8
