### ISSUE TITLE
Not enforcing rules

### ISSUE THREAD

**Issue by buddyackerman** [TrimbleSolutionsCorporation/VSSonarQubeExtension#261]
After installing the extension I restarted VS and opened my solution and connected to my SonarQube server.  It updated all the projects in the solution but it doesn't appear to actually apply an rules.  I purposely changed a file that has a rule violation and it doesn't mark it as a problem.  I right-clicked on one of the projects and under the SonarLint Connected Mode menu it shows the project set to Automatically Detect.  I'm using version 2.10.0.1098. on VS 2015.

**Comment by jmecosta** [comment]
Hi

This is not the SonarLint extension, if you have this installed uninstalled
and use only the SonarLint extension.

If the problem remains please reach to the guys in the Google groups for
SonarLint they should be able to help
