### ISSUE TITLE
 Blank spaces log route

### ISSUE THREAD

**Issue by TecnicoOMC** [TrimbleSolutionsCorporation/VSSonarQubeExtension#275]
We have problems when the routes contain blank spaces.
The first parameters it takes well but the one of the logs as it does not have quotes gives error.
 /l:FileLogger,Microsoft.Build.Engine;logfile=C:\File 1\BuildLog.txt;Encoding=UTF-8
The complete sentence is:
"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "C:\File 1\Pro.sln" /v:Detailed /p:SonarQubeTempPath="C:\File 1\.sonarqube" /p:Configuration=Debug /p:Platform="Any CPU" /t:Clean;Build /p:VeraTaskEnabled=true /p:RatsTaskEnabled=true /p:CppLintTaskEnabled=true /p:CppCheckTaskEnabled=true  /l:FileLogger,Microsoft.Build.Engine;logfile=C:\File 1\.cxxresults\BuildLog.txt;Encoding=UTF-8 /noconsolelogger /m:1 
Is it possible to change it?

**Comment by jmecosta** [comment]
Well yeah, but on the wrapper side

**Comment by jmecosta** [comment]
moving ticket to wrapper

**Comment by jmecosta** [comment]
@TecnicoOMC you can use 1.9.17 https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases/tag/1.9.17
